---
collections:
  - name: community.general
    version: 4.4.0
  - name: community.sops
    version: 1.2.0
  - name: ansible.posix
    version: 1.3.0
  - name: kubernetes.core
    version: 2.2.3
roles:
  - src: xanmanning.k3s
    version: v3.1.0
  - src: patrickjahns.promtail
    version: 1.15.0
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker
    version: 4.1.3
