---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./prometheus-rule.yaml
  - ./secret.sops.yaml
  - ./dashboard
  # - ./helm-release.yaml
configMapGenerator:
  - name: loki-alerting-rules
    files:
      - loki-alerting-rules.yaml=loki-alerting-rules.yaml
generatorOptions:
  disableNameSuffixHash: true
