---
collections:
  - name: community.general
    version: 5.6.0
  - name: community.sops
    version: 1.4.1
  - name: ansible.posix
    version: 1.4.0
  - name: kubernetes.core
    version: 2.3.2
roles:
  - src: xanmanning.k3s
    version: v3.3.0
  - src: patrickjahns.promtail
    version: 1.18.0
  - src: geerlingguy.pip
    version: 2.2.0
  - src: geerlingguy.docker
    version: 5.2.1
