---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos
  # - ./loki/ks.yaml
  - ./grafana/ks.yaml
  - uptimerobot
  - unifi-poller
  - goldilocks
  - vertical-pod-autoscaler
  - vector
  - node-problem-detector
  - snmp-exporter
  - ./gatus/ks.yaml
