---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - kube-prometheus-stack
  - thanos
  - loki
  # - pushgateway
  - grafana
  - uptimerobot
  - unifi-poller
  - goldilocks
  - vertical-pod-autoscaler
  - vector
  - node-problem-detector
 # - snmp-exporter
