---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cdr-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://code-server-boilerplates.github.io/charts
  timeout: 2m
