---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jupyterhub-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://jupyterhub.github.io/helm-chart/
  timeout: 2m
