---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 10m
  image: ghcr.io/k8s-at-home/plex
  # accessFrom:
  #   namespaceSelectors:
  #     - matchLabels:
  #         kubernetes.io/metadata.name: media
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
    namespace: flux-system
  filterTags:
    pattern: '^v(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)\.(?P<mod>\d+)-(?P<hash>[\d\w]+)$'
    extract: "$major$minor$patch$mod"
  policy:
    numerical:
      order: asc
    # semver:
    #   range: ">=1.2.5"
