---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-operator-chart
  namespace: flux-system
spec:
  type: oci
  interval: 15m
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
