---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal
  namespace: downloads
  labels:
    app: terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
        - name: alpine
          image: alpine
          command:
            - /bin/sh
            - -c
            - while true; do
              sleep 600 &
              wait $!;
              done
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
