---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./traefik/crds.yaml
  - ./grafana-agent-operator/crds.yaml
  - ./external-snapshotter/crds.yaml
  - ./external-dns/crds.yaml
  - ./velero/crds.yaml
