apiVersion: v1
kind: Secret
metadata:
    name: pmm-secret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:H1IZy5L47N0Xw4rDnWTuIEvyPnE=,iv:8ejbzov49DvkOQYnj9qg+uxDOvpScS91ldVCi96HmdY=,tag:qjpYIEyRgcBRyF3aiYllWw==,type:str]
    MDBLIST_API_KEY: ENC[AES256_GCM,data:TPTniIJnxONNJT0HELwUvckk0/J1dilvBQ==,iv:oKPYNcPsGkphZbgPJt/7eEaHqbXcExaRC/S6taGYA4Y=,tag:bSA0VZ8xl66HnGflcML6xA==,type:str]
    OMDB_API_KEY: ENC[AES256_GCM,data:QCJmiJlXSaQ=,iv:8roARS1GRQGcM52EoDh2MGWrBPKEH14gRUGgBJm4UNM=,tag:ZvaaUlI/pktvazc1hyRPEA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:x4adwoULtDOb1Vb5nfoRlL5gACCgrtzwlbcbcwQqyOQ=,iv:A7HaqfPH2oth3mbsPD/g4KAPrvMasOT+cBbJZJpO2ss=,tag:4WpdYiKNSYzKACGwdf7NvA==,type:str]
    TRAKT_CLIENT_ID: ENC[AES256_GCM,data:p8PpM/aM0t8isC+2DUSjW6yzpcKvsVJ4HQtrb8b2pRkSUn9zSCEAokOik3OM4bEtWTvRmAUaNsA2u6fdz01NJw==,iv:KxBbgEmBenfLGhbBuSIinqaldhxdrXaJ3QMunOo7wtU=,tag:wRaraf1dpL3Y9rmtf0R2tA==,type:str]
    TRAKT_CLIENT_SECRET: ENC[AES256_GCM,data:apyw+kwJa/yrVv3QMNB43NtcsvzQqMuQWxhAx7OVgDFH3ABiJLXdvh2YDfzKQh9vivGCml3PtAhIJ7hebIULlg==,iv:mIDbmkzHhmdorFRAPWjTrZXtuPLKMeYd5FA9AOWnBmw=,tag:V9ESEiSShRsg+fKUJB4XXA==,type:str]
    TRAKT_ACCESS_TOKEN: ENC[AES256_GCM,data:AVCKvzXqf9Lc3rOVSKQSZr78rnYBnDXq0QCMHG68rKE+DGCiK2g4sFD7eCtXjoFHVWRoDdsPBK8GEfih4Omt6A==,iv:tJdUKYRYHp8j/3qYbbZWpQQ3NEPVmlILM98VklFJxOw=,tag:sB7urGwCwKfjO4KNiPkr4Q==,type:str]
    TRAKT_EXPIRES_IN: ENC[AES256_GCM,data:EDF4stTC,iv:9eBPiVjBkW1rthTrHM2kI8AQwrbrNpcBDuLQJG/fEIE=,tag:6e8xz1xY4Gpde1LG2GRq8A==,type:str]
    TRAKT_REFRESH_TOKEN: ENC[AES256_GCM,data:ClbboV96u2vnW/BhFHTGg2WvCqpBn+hTEPL/Eeg6sUcre5kxrww0E0YWUEpF7q4bkmQSiDfD0c78TrptWaDwNA==,iv:msAH7Ac+iCR4VJMu55hA+o/5DMqrJ9bBuoIc3zrna0w=,tag:YvWxtr6u+HAgr9SvrmFecw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:OAIOL0M3Dbuo1HIIxViBOgv+eqLirHBMuH2NH5l+AIcKP5NKhBKWzQyjiLff3Urz7rbXz3pV/ZA+Lzr+Dandh+QspaehL64DT7jFggaA3NiJq/s3lO2BL0tBqOotMkkjILZcd/n2wEWM9NzI0q6ZPUU3kPuyfGWO,iv:L4cTvS+O1FW97WHWgMKbT18Ql7xYqPH4JvLG6GUPJCo=,tag:CIvnyAeIBi1kXbnihb513A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hr5v66mq2rtflw8vrzmdlaku48v0j5l2wr58lrdmxqp5decczugs3rr6yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa1dXeWpNVm5zU3hzYnNY
            R3ZnWFFJcjRVVmE2ZndKY3hZSlN0dUxaZkdZClpPZldUU2ZhdzEwK09JdlJQcFRu
            QlpPNUgxSHRDQUhKQlgwSGdrMGNtUkkKLS0tIDVrWi9DSXJrSklEV0RjQTRLNGIv
            ejJsRm8rbWFpdEMwYmh1N2tnSHIzaEUKBmwaMrZkYqkZuxwTX56rnC6uJj/bjJjk
            NRH7k/JnPLEOf9QbDDHrfHMjWjhI2xAXpKaqc201gflH/KWUO03Mwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmlRdVJSTkpOY0ZLVnFj
            VUpYNHlES1lTeE9uYm5tMDNqd2dtWG1OMHprCkxROXIvQ1hsRmFmUjIySnBCRU9D
            Smh3UnF3VlpZb3d1MVdodGJqZ3JGSFUKLS0tIHVtYjYraHFVOEFQR3RwUW1VeDlr
            QUFFbEwxcFQvVlZPVzBHbEZ6cEwzVjQKqN3i4EunV+XbLhrmVwO0sGpAHHxvA1Lm
            hyQDH5Hzko02LXa/LUZ3Z8ZdsWuwxkj4FHJ47oIzeZJistCbqjSacQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T17:46:39Z"
    mac: ENC[AES256_GCM,data:gFwzoZhrE/Z8O6M48IZIE3rghyzWntYFLYFt+jiKW4qrXGsz/bzBo/ml72eCstDYzvHq2MS9HnaoITkqrgNUQa7eLeD6kwkzjhHauU8NE0wQGV30XkHSNlgkg9vJQcAlRM7m+MwqCuA0Y5HZd7m0VZJKxkyTUTIb6Xb7Qiegqzg=,iv:OVzPRixthB0vlmc2qZbl2GiQrM2KOZCT2IgtVMlaNqM=,tag:ZdEw9lDBRzlxKcymktp81g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
