apiVersion: v1
kind: Secret
metadata:
    name: pmm-secret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:cBhXN8eDjdFsDGeQtfaQvspug88=,iv:H4lGyMTi4mKTKUDbIE5jMWQRi3dqLb6kVdFQ/ILQUE8=,tag:fslWRCqRNbSVMW+mJEIiyQ==,type:str]
    MDBLIST_API_KEY: ENC[AES256_GCM,data:fE0MkVg0CWMJqz24WGrKqmgm9ItgSfyePQ==,iv:Ns00jgTT7veaU0rMymbyldQhnq5r1Xdk1YWXvG3dD44=,tag:J8AaJMkCqpmGvb0geFOQxg==,type:str]
    OMDB_API_KEY: ENC[AES256_GCM,data:RaZELWJre0U=,iv:1ENz6fokCeLMwOukqRYIAAigcqqTlyyVxY6mQ6w1XXE=,tag:IFtZN0kfAKyf5GVCewhYOA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:W0Z+zAdaPyLioQrTY9iL7xy+sq7U+fE/BUaqDVxKC1Q=,iv:744L/wZqRyI3D6l3JWiAkjJwz5p3AfgQeuZLWWMYcYM=,tag:tbPiEPoQ0COT8PHYf33N6w==,type:str]
    TRAKT_CLIENT_ID: ENC[AES256_GCM,data:MKJAkznIp2XunoEZvYIpTAs466RVLWWI65VN20qAU4mgLN29a7Le5Kct65vCYA0ZjR8I0qdEalB5zDAlaNSmzA==,iv:KvxI406G/ZLsxs9i+SjWgpCMgl9DD2/d4pox04xDL24=,tag:qOUxZaOeXZ2MnKeEUoYmvQ==,type:str]
    TRAKT_CLIENT_SECRET: ENC[AES256_GCM,data:4ITlVEmDwyGCKb0NOL7XFLZy+Ie1YoTjrIubeERgIwe0R/qCXFUCAipmw4RRic7gjCn0c5pioxSOpQ/P6ol2Ag==,iv:Fo49iU2WaqsOm97G3NavoW0/9Twy7YEUAnazx8iBeZc=,tag:kO+r8hbWmlGFu2nMesxX/w==,type:str]
    TRAKT_ACCESS_TOKEN: ENC[AES256_GCM,data:6aQMnL6oIo9y3GRahgeFOD53XRtzht+uJsLSNAF/5S5coUs2s9mzOr/vmgI1Fqrh5K/nd3buOgEW8AD3GmfAkA==,iv:9jXwWr3YZ8oyMLlTbhDHMMZPSvPIk1HVHXVEIqDc7Lc=,tag:yWJvNUeBFQizfVSRrfdLRQ==,type:str]
    TRAKT_EXPIRES_IN: ENC[AES256_GCM,data:LUu+ETpi,iv:5hk/O6TH39PbkR3EIieeYjPwVTh+2GUUkpruXOts7n8=,tag:fcknLQvY10TPFRh5/B7wqw==,type:str]
    TRAKT_REFRESH_TOKEN: ENC[AES256_GCM,data:jVqZ/uKBx+Nz5tvrE9WhOXM9QMQIPeLt6qufMp8l6x2E++IVfVaMvvpC58BYVMKyVvE50oikfgF5M0qe0bzs7Q==,iv:sE8CKJyCtj5oMRYLC6i84crDii8msBvo+UZFnupiXzM=,tag:q/aNxnAzS7gtC6okpsjH9w==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:SPdBvGMtUNj0Fu86HJvqOAl8b6gf2jNgHyjJJvsADwSPJVINMQmckCo4XlJxiqEPExx2PqUr32JQxTpUK5+6bO4n8p8+iBt1uZPIj/X8rBoS7FYkkvuG73+9l2NXVLnDKW0xgPEhgtew0/knpOPULAOzOCFnw37Y+g==,iv:Zihw3KS8ce57yAqB0jCdqcXkRBx0FWSFjM2mJ7Rt020=,tag:ssoqZBA7Qayl6vabswew3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hr5v66mq2rtflw8vrzmdlaku48v0j5l2wr58lrdmxqp5decczugs3rr6yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSzZycHZ2WEU3c2RkZE5E
            eVZDNXU4RUkxRGhvRUV5VHArU1FtWEZnaHpzCnljNFhzbW5JdnhwSmJ2QzhEbnBY
            RFYxZ0U2dGI2S1lNTFhCeDRSWkwrMEEKLS0tIFR0TFZKUTZscGhoL1h5NjlqeExJ
            MGtHVnBoZkhXdjJIWHo5RUdIem91TTAK6auAh/WC8y/Fw1cLoxox+cTf1WL96lzQ
            WCiyEoWdlA3tfAd3e/KBx3HL67+8A9C0XU7+rQD+A4RirrgaYD3EXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQlBtWGVZU3hKSVFDTzQx
            TGphRWliUnJjZ0VXRXhXNnZrNS9KVzg3SXdRCndjTDZPcXRsQ3l2SS9XQUx1d0ds
            bHN5OUxXZE9vRW1uMHhEZVlZWi9mRjAKLS0tIENFaExvN21QSDJqVVRCRmNEaGhh
            R1RpWExqRzViQzFYU3RSRThRazJmczQK/N/DxEKM5c7uJY31ulsZmxhD/MsHSSKV
            RdA/+Pg30DaVW0SvOJAzNZx6iDg6rPAl+Tct1c6VK5ffJNrqav4QXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T22:57:23Z"
    mac: ENC[AES256_GCM,data:u6+x1sLzoFnN6yj7DQT9+WAZaUva2c16r8pwIiO9V1IrgSVBpFTKLZaHzswYis9NQujAzmntkhcBR//qecyqbVZ6OzTuQu1U/MjoV7Kh9zxkMEwhMwC7W6uOVIIjcHtE1IDqlp0uM/yPShGppBDHXiurCWn2zMmSTnn9cUNVnlE=,iv:w/godQVv7vz2rgBAht1dkdLzGaCdo7bLsUF260TSAyc=,tag:jCN5bCWQEnG+nNzFVX4jFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
