apiVersion: v1
kind: Secret
metadata:
    name: pmm-secret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:s+pA6AEf2uHHIAVsKInxds4JcqU=,iv:WVlhhON56S8CjKmpyjzT14+ubW8j7aBQb4DxKjcFgIw=,tag:mfVF4Iu4FJY75WRxCTQcGg==,type:str]
    MDBLIST_API_KEY: ENC[AES256_GCM,data:kr67SMnu3Dpksl7S0EWJCN7hjkngLahGJw==,iv:p3DViQtRECBwa094bO3miDGhh26vZ4CwCQfXAxxQN+8=,tag:uOR3kD5PZvxyqw8LGmxLPg==,type:str]
    OMDB_API_KEY: ENC[AES256_GCM,data:A2ySRvQbaYI=,iv:cYX9KYQh45pCJToOAPGRWj32Zg7tnFrAXXUFpuunCuc=,tag:vB3YVc5aoWD0BQoFJFmTSg==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:/NskEvq07qGIiB9U0KLjSRFiEfSMzzE5wpxZuzGiIeU=,iv:7xNKI5kkY3S5A+6NtnVhs7A0nTf+0rvCYkpH1MluLBE=,tag:5vNkCzqYz5HRNEH/+QYTpw==,type:str]
    TRAKT_CLIENT_ID: ENC[AES256_GCM,data:Tew1NkYjCl7VYbVnLGIH9YxH1eyakEY2VQDYgMXO/llN7UuPXrdJKt0Bb6SKXVceAgXHUbnlGXnxbHVv2zfkiA==,iv:I2+4dRtzv1ddg4WrOKA1jCoxmkPb0tFavUswJEPPtfQ=,tag:ROIdvtV2sDc4JqTnQMHTRA==,type:str]
    TRAKT_CLIENT_SECRET: ENC[AES256_GCM,data:dDEDWi/PlaPubtfi//64NXXmnpx6VnhAWHK/sJUdKa/bcWz1sWZRSZGuy8ayoiOjc2DZfQYbWq/iA+OfhwjJ6A==,iv:zSMY0pY/nQ9SWuCEGlstGBUwrSQKFuKs26hbw3tHYqY=,tag:zqIzPrb/agpCDDIjMLr2WA==,type:str]
    TRAKT_ACCESS_TOKEN: ENC[AES256_GCM,data:GS3e+6tJayw98KAuUDLY3X/wa8QrGD+K9UopfIenu3vp1qbWEbE+TFCdH5Ueww6JJPwYF8Ry/zBpKpeeqP7ECw==,iv:/bf1ZsGpQnWIX9eZ8jMP1AXSVi0fvMLSrW7o8kUn6ng=,tag:6ULYiDH/WaqJVYLLRyvGlQ==,type:str]
    TRAKT_EXPIRES_IN: ENC[AES256_GCM,data:x6ydBm1d,iv:J70nx24Jrk1jFj3pYxAspojbbcmHeO3ci1dcLmv7mzw=,tag:YU/sdaOLqIFI8S7goEfVSA==,type:str]
    TRAKT_REFRESH_TOKEN: ENC[AES256_GCM,data:rq+jv0ZeQfU7u8Qdfj8hAh4JGtb+QkSkdyb//ggYx6fIBKL5q8V2cjadd69XCxwPSc2BilptbOJXM8cbo0jcEA==,iv:GptaFcWoMTsVtTXtmJFl23AXiWMy2RyXu+X/GtEG+tU=,tag:h/of0FBGWbULRzkAYYbBpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hr5v66mq2rtflw8vrzmdlaku48v0j5l2wr58lrdmxqp5decczugs3rr6yt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcW9KeFdTejg4MmlwMUpS
            eHpRd245YXFQSnBnUWtXOHovejJlUXQrZG04CjVwcS8yeFZkUVg2c0IyQ1RjNDQ0
            cWUyeGxpN2I1Vm1kVW5zTFpyWUo3ZW8KLS0tIG1LSU4rTEZSemN6V1Qvc3FOYkxQ
            V3BMUS9OZUZ3Unk2d1pkZTBsaUZyenMKUNZR/chvVncAQxiZrJE1Kvh/fjHJuyVP
            4AKQvGJHqcQHfv3jsXXp6GeHCZ5mm3z67B3sK6NIvK1X4i0hjlDgCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rp9r7wvsgy6zcl3j4v7kvnrv29sawvqhlm759j9x6zvs0f9ry4kqtmajrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VUwzOU9ZSkZSUE1zVGM2
            aVpJbUM4UDFadThMTlZZTlViNElYbjN1VldjCnpGcExJQnRsNnVJUUVhTWVRSnFC
            M3JZWGxGS0FLU3JFR0c3dG5NMzJpRm8KLS0tIHR6OXdVaWRUR3QzbUhWYkJGeVc3
            azlzUmxtRWM4MHo4bE50cFFUS1g5MkkKeBiO/FdnJ3NhuWI50b0Fj1wuG0dP3+F9
            Bo5In67a23/Fm1skULYAJ2MuBQKkHtumNgfRFUzIRFXoKC32AdFEmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T17:06:06Z"
    mac: ENC[AES256_GCM,data:2A9SFcng+S2hIBUg9xRQc1z98JQMsP3NxkRV4CgSCpyVZvaXxvKnoWuSfa7hwcvgKU0T+9eZUaG/npAGmyWiA1awmVH8gV3AHMQx9+eBhUvP8kDMFdfoFXY0G3qHeDx9VMLPIvf6ksHt641FAVoYKG5q8cmGuus3ecuLKG9hgVs=,iv:gC8YXgisczEVwIgncRUpAYo9ZXywCrgj5cYr8eFv9xo=,tag:jCbxgq3leD0q4yNPORacLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
