---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - error-pages.yaml
  - classic-traefik.yaml
  - auth-ldap-authentik.yaml
  # - media-lidarr-bypass.yaml
  - home-home-assistant.yaml
  - home-emqx.yaml
  - home-hass-db.yaml
  - networking-camelus.yaml
  # - home-zwavejs-wss.yaml
