---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - error-pages.yaml
  - classic-traefik.yaml
  - media-books.yaml
  - media-radarr-uhd-bypass.yaml
  - media-sonarr-uhd-bypass.yaml
  - home-home-assistant.yaml
  # - home-zwavejs-wss.yaml
