---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack-charts
  namespace: flux-system
spec:
  interval: ${DEFAULT_HELM_REPO_INTERVAL}
  url: https://charts.jetstack.io/
  timeout: ${DEFAULT_HELM_REPO_TIMEOUT}
