---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media-pv
  - plex
  # - calibre-web
  # - lazylibrarian
  # - overseer
  # - radarr-uhd
  # - bazarr
  # - lidarr
  # - tdarr
  - sonarr-uhd
  # - readarr-audio
  # - mylar
