---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./priority-class.yaml
  - ./media-pv
  - ./plex
  # - ./books/audiobookshelf/ks.yaml
  - ./books/calibre
  - ./books/calibre-web
  - ./books/lazylibrarian
  - ./books/readarr-audio
  - ./books/readarr
  # - ./books/mylar
  - ./bazarr
  - ./lidarr
  - ./tdarr/ks.yaml
  - ./sonarr
  - ./radarr
  - ./overseer
  - ./prowlarr
  - ./tautulli
  - ./plex-meta-manager/ks.yaml
  - ./plex-trakt-sync
  - ./stash/ks.yaml
  - ./recyclarr/ks.yaml
