---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./priority-class.yaml
  - ./media-pv
  - ./plex
  - ./books/audiobookshelf/ks.yaml
  - ./books/calibre
  - ./books/calibre-web
  - ./books/lazylibrarian
  - ./books/readarr-audio
  - ./books/readarr
  # - ./books/mylar
  - ./bazarr
  - ./lidarr
  - ./tdarr/ks.yaml
  - ./sonarr
  - ./radarr
  - ./overseer
  - ./prowlarr
  - ./tautulli
  - ./plex-meta-manager/ks.yaml
  - ./plex-trakt-sync
  - ./stash/ks.yaml
  - ./recyclarr/ks.yaml
  # - ./music-assistant/ks.yaml
  - ./navidrome/ks.yaml
  # temporary until I figure out a sustainable way to do cross-namespace extensionRefs
  - ./middlewares/chain-no-auth.yaml
  - ./middlewares/bloopnet-xyz-auth.yaml
  # disable until account detangling is figured out
  - ./ytdlp-sub/ks.yaml
