---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-db-backup.yaml
  - pvc-config.yaml
  - ghost-secrets.sops.yaml
  - ghost-mysql.yaml
  - routers/admin-route.yaml
  - routers/redirect-tgr-lilj.yaml
  - routers/content-route.yaml
  - helm-release.yaml
  - observability/ghost-gatus.yaml
  - observability/ghost-mysql-gatus.yaml
