---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../../../components/common
commonLabels:
  app.kubernetes.io/name: musicbrainz-picard
  app.kubernetes.io/instance: musicbrainz-picard
resources:
  - ./helm-release.yaml
  - ./pvc-config-v1.yaml
