---
name: Invalid Template

on:
  issues:
    types:
      - labeled
      - unlabeled
      - reopened

jobs:
  support:
    runs-on: ubuntu-24.04
    steps:
      - uses: dessant/support-requests@47d5ea12f6c9e4a081637de9626b7319b415a3bf # v4
        with:
          github-token: ${{ github.token }}
          support-label: "template-incomplete"
          issue-comment: >
            :wave: @{issue-author}, please follow the template provided.
          close-issue: true
          lock-issue: true
          issue-lock-reason: "resolved"
