---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - auth.yaml
  - metallb-system.yaml
  - networking.yaml
  - storage.yaml
  - monitoring.yaml
  - tigera-operator.yaml
  - media.yaml
  - vpn-gateway.yaml
  - velero.yaml
  - downloads.yaml
  - database.yaml
  - rook-ceph.yaml
  - home.yaml
  - blogs.yaml
  - emqx-operator-system.yaml
  - mysql-operator.yaml
